applications:
- services:
  - Monitoring and Analytics
  disk_quota: 1024M
  host: thinkibm-consumer
  name: ThinkIBM Consumer
  path: .
  domain: mybluemix.net
  instances: 8
  memory: 512M
env:
  NODE_ENV: bluemix