version: '2'

services:
  make-ssh-keys:
    build: config-ssh-keys
    container_name: make-ssh-keys
    volumes:
      - config_ssh_keys:/keys:rw

  esmaster:
    build: elasticsearch-master
    container_name: esmaster
    networks:
      - ibmnet
    volumes:
      - es_data:/usr/share/elasticsearch/data
    restart: always

  fakesmtp:
    image: munkyboy/fakesmtp
    container_name: fakesmtp
    volumes:
      - /tmp/fakemail/:/var/mail
    networks:
      ibmnet:
        aliases:
          - smtp.think.ibm
    restart: always

  datapower:
    build: datapower
    container_name: datapower
    networks:
      ibmnet:
        aliases:
          - dp.think.ibm
          - api.think.ibm
    environment:
      - DATAPOWER_ACCEPT_LICENSE=$ACCEPT_LICENSE
    restart: always

  apim:
    image: ibmcom/apiconnect:manager-${APIC_VERSION}
    container_name: apim
    mem_limit: 2048m
    volumes:
      - apim_ihvar:/ihvar
      - apim_wip:/wip
      - config_ssh_keys:/keys:ro
    environment:
      - MANAGEMENT_CLUSTER_HOST=mgr.think.ibm
      - PORTAL_PRIVATE_KEY=/keys/portal
      - PORTAL_PUBLIC_KEY=/keys/portal.pub
      - PORTAL_LB=developer.think.ibm
      - ES_HOST=esmaster
      - ES_PORT=9500
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SENDER
      - LOGSTASH_HOST=ibmlogstash
      - ACCEPT_LICENSE
    networks:
      ibmnet:
        aliases:
          - mgr.think.ibm
    depends_on:
      - fakesmtp
      - make-ssh-keys
      - esmaster
    restart: always

  ibmportal:
    image: ibmcom/apiconnect:portal-${APIC_VERSION}
    container_name: ibmportal
    environment:
      - PORTAL_LB=developer.think.ibm
      - PORTAL_PUBLIC_KEY=/keys/portal.pub
      - APIC_HOST=mgr.think.ibm
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - SMTP_SENDER
      - ACCEPT_LICENSE
    volumes:
      - ibmportal_var:/var
      - ibmportal_etc:/etc
      - config_ssh_keys:/keys:ro
    depends_on:
      - make-ssh-keys
      - apim
      - datapower
    networks:
      ibmnet:
        aliases:
          - developer.think.ibm
    restart: always

  consumer:
    build: consumer
    container_name: consumer
    networks:
      ibmnet:
        aliases:
          - consumer.think.ibm
    restart: always

  stubsvcs:
    build: stubsvcs
    container_name: stubsvcs
    networks:
      ibmnet:
        aliases:
          - services.think.ibm
    restart: always

  logstash:
    image: ibmcom/apiconnect:logstash-${APIC_VERSION}
    container_name: ibmlogstash
    environment:
      - ES_HOST=esmaster
      - MGMT_HOST=mgr.think.ibm
      - DB_HOST=mgr.think.ibm
      - ACCEPT_LICENSE
    networks:
      - ibmnet
    depends_on:
      - apim
      - esmaster
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd!
      - MYSQL_DATABASE=think
      - MYSQL_USER=student
      - MYSQL_PASSWORD=Passw0rd!
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    networks:
      ibmnet:
        aliases:
          - mysql.think.ibm
    restart: always

  nginx:
    build: sni-proxy
    container_name: nginx
    environment:
      - PORTAL_DNS=developer.think.ibm
      - APIM_DNS=mgr.think.ibm
      - GATEWAY_DNS=api.think.ibm
      - DATAPOWER_DNS=dp.think.ibm
      - CONSUMER_DNS=consumer.think.ibm
      - STUBSVCS_DNS=services.think.ibm
    ports:
      - "443:443"
    volumes:
      - /var/log/nginx:/var/log/nginx
    depends_on:
      - ibmportal
      - datapower
      - apim
      - consumer
      - stubsvcs
    networks:
      - ibmnet
    restart: always

volumes:
  config_ssh_keys:
  apim_ihvar:
  apim_wip:
  ibmportal_var:
  ibmportal_etc:
  es_data:

networks:
  ibmnet: